# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be86741c75b3cabd08c275efd208f28d6003548ebdb858b1b393dc6ed6dfa3b1d62c4f918c8d11ac680c5971accece7b32a859e3775f010dd9ecd5a009b299a1

test:
  secret_key_base: 41ee108346d6a3551c3b705527b1e98554805c158d5fc85999ea730287f687f7c3b59acf2123105e11b98482a10fb0c1b67fa2f6020940cc56ca069054a78b88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
